### ISSUE TITLE
Request for default docker images

### ISSUE THREAD

**Issue by Skeen** [cosmo0920/fluent-bit-go-loki#14]
Will you consider throwing pre-built docker images on dockerhub?

**Comment by cosmo0920** [comment]
I'd published the base image in DockerHub.
Thanks for the report! :yum:

**Comment by Skeen** [comment]
The links in the Readme file to the images does not work for me.

They point to:
https://cloud.docker.com/repository/docker/cosmo0920/fluent-bit-go-loki/tags

However this link works for me:
https://hub.docker.com/r/cosmo0920/fluent-bit-go-loki

You can try to confirm this using incognito mode.

**Comment by cosmo0920** [comment]
I've fixed it. Thanks again!　:smile:
