### ISSUE TITLE
How to add the parsed log fields as Labels

### ISSUE THREAD

**Issue by Vaka82** [cosmo0920/fluent-bit-go-loki#9]
#### Problem
How to add the parsed log fields as Labels. So that i can search using those parsed fields in Grafana.

I've parsed the log lines using regex as below - 

{"userid":"test",component"=>"test1", "page"=>"test2"}

I would like to add these labels and search using these labels in grafana.

**Comment by cosmo0920** [comment]
There is no support this feature for now.
And I don't want to add this feature....

**Comment by tfchan0** [comment]
Thanks for this plugin!  Along the same line, that means it's not supported to take existing labels (keys) in the logline as Loki labels at this time?  Thanks.

**Comment by Vaka82** [comment]
I've added that logic to label those required fields but that made the search terribly slow. Often times it was crashing. 
Also whike loading the data it's throwing data out of order exceptions...looks like loki need those labels to be unique...

**Comment by tfchan0** [comment]
I believe so.  I followed the tutorial by adding worker_id/hostname (I'm sourcing from Fluentd).  Then it's fine afterwards.

**Comment by tfchan0** [comment]
@Vaka82, would you be able to share the added logic for parsing log fields as Label?  Thanks.

**Comment by Skeen** [comment]
@Vaka82 I'd be interested in this as well, having the option to extract at least a few labels from the json would be massively helpful.

**Comment by cosmo0920** [comment]
This feature will be included in v0.3.0.
It is developed on https://github.com/cosmo0920/fluent-bit-go-loki/tree/support-dynamic-labels.

**Comment by cosmo0920** [comment]
v0.3.0 is published. Closing.
